apiVersion: v1
kind: Service
metadata:
  name: bookinfo-dev-ratings
  namespace: {{ .Values.ratings.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: bookinfo-dev-ratings